#!/bin/sh

echo "Mounting things..."

mount -t proc none /proc
mount -t sysfs none /sys

echo "Done mounting things"

echo "Configuring /dev..."
mount -t tmpfs -o size=64k,mode=0755 tmpfs /dev
mkdir /dev/pts
mount -t devpts devpts /dev/pts
sysctl -w kernel.hotplug=/sbin/mdev
mdev -s

echo "Here, have a shell..."
exec /bin/sh
